# Generated by Django 4.2.19 on 2025-03-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="updated_at",
            new_name="modified_at",
        ),
    ]
