# Generated by Django 4.2.19 on 2025-03-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="email",
            field=models.EmailField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="resume",
            name="resume_summary",
            field=models.TextField(db_index=True),
        ),
    ]
