# Generated by Django 5.1.3 on 2025-03-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0003_resume_original_content_resume_pdf_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="cover_letter",
            field=models.TextField(
                blank=True,
                db_index=True,
                help_text="Professional cover letter of the candidate",
            ),
        ),
    ]
