# Generated by Django 5.1.3 on 2025-03-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0004_resume_cover_letter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="cover_letter",
        ),
    ]
