# Generated by Django 5.1.3 on 2025-03-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0005_remove_resume_cover_letter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resume",
            old_name="language",
            new_name="languages",
        ),
    ]
