# Generated by Django 5.1.3 on 2025-03-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_rename_language_resume_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='update_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
