# Generated by Django 5.1.3 on 2025-03-20 22:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(db_index=True, max_length=255)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?1?\\d{9,15}$"
                            )
                        ],
                    ),
                ),
                ("cover_letter_content", models.TextField(db_index=True)),
                (
                    "company_name",
                    models.CharField(help_text="Company name", max_length=255),
                ),
                (
                    "job_title",
                    models.CharField(
                        help_text="User job title", max_length=255
                    ),
                ),
                (
                    "parsed_content",
                    models.TextField(
                        db_index=True,
                        help_text="Professional cover letter of the candidate",
                    ),
                ),
                (
                    "generated_content",
                    models.TextField(
                        blank=True,
                        help_text="Original markdown content from AI generation",
                    ),
                ),
                (
                    "pdf_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the generated PDF Cover Letter",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cover_letters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
