# Generated by Django 5.1.3 on 2025-03-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_letters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='update_generate_content_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
